-- MySQL Script generated by MySQL Workbench
-- Fri Mar 19 03:20:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telegram_id` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `availability` INT NULL DEFAULT 0,
  `state` VARCHAR(45) NULL DEFAULT 0,
  `last_update` DATE NULL,
  `region` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `availability_update` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_disponibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_disponibility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telegram_id` VARCHAR(45) NULL,
  `time_update` DATE NULL,
  `availability` INT NULL,
  `region` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user`
    FOREIGN KEY ()
    REFERENCES `mydb`.`users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`managers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `last_update` DATE NULL DEFAULT 'Date()',
  `telegram_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`users_active`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_active` (`id` INT, `telegram_id` INT, `name` INT, `surname` INT, `availability` INT, `state` INT, `last_update` INT, `region` INT, `province` INT, `availability_update` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`users_for_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_for_search` (`id` INT, `telegram_id` INT, `name` INT, `surname` INT, `availability` INT, `state` INT, `last_update` INT, `region` INT, `province` INT, `availability_update` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`users_not_active`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_not_active` (`id` INT, `telegram_id` INT, `name` INT, `surname` INT, `availability` INT, `state` INT, `last_update` INT, `region` INT, `province` INT, `availability_update` INT);

-- -----------------------------------------------------
-- View `mydb`.`users_active`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_active`;
USE `mydb`;
CREATE  OR REPLACE VIEW users_active as select * from users where region is not null and availability = 1 and name is not null and surname is not null;

-- -----------------------------------------------------
-- View `mydb`.`users_for_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_for_search`;
USE `mydb`;
CREATE  OR REPLACE VIEW users_for_search as select * from users where region != null and province != null and name != null and surname != null;

-- -----------------------------------------------------
-- View `mydb`.`users_not_active`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_not_active`;
USE `mydb`;
CREATE  OR REPLACE VIEW users_not_active as select * from users where region is not null and availability = 0 and name is null and surname is not null;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
